name: integrate

on:
  pull_request:
    branches:
      - master
      - release-*


jobs:

  test_all:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha  }}
        path: go/src/github.com/${{ github.repository  }}

    - name: Build the docker-compose stack
      run: TIUP_CLUSTER_ROOT=${{ github.workspace   }}/go/src/github.com/${{ github.repository  }} ./docker/up.sh --daemon
      working-directory: ${{ github.workspace  }}/go/src/github.com/${{ github.repository  }}

    - name: Check running containers
      run: docker ps

    - name: Run test suite
      working-directory: ${{ github.workspace  }}/go/src/github.com/${{ github.repository  }}
      run: |
        # should not use -it
        # ref: https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty
        docker exec  tiup-cluster-control bash /tiup-cluster/tests/run.sh
        # source ~/.bashrc
        # ./tests/run.sh

    - name: Output cluster debug log
      if: failure()
      run: "cat ./tests/*.log"
      working-directory: ${{ github.workspace  }}/go/src/github.com/${{ github.repository  }}

